### ISSUE TITLE
Add random Stock Featured Images

### ISSUE THREAD

**Issue by cinakur** [InteractiveDesignAndDevelopment/cs-news-export#5]
(From Matt's List)
From https://github.com/InteractiveDesignAndDevelopment/wp-news/issues/54

**Comment by Sporkyy** [comment]
@maconmatt Should these use the same images as the MCMS news export?

**Comment by Sporkyy** [comment]
Added.

**Comment by Sporkyy** [comment]
Nope, didn't work.

**Comment by Sporkyy** [comment]
Fixed in 01d561db5015f79250874c6359b9b2478eff9f37
